-- CreateTable
CREATE TABLE "TAPRI_CHAT_DETAILS" (
    "ID" SERIAL NOT NULL,
    "TO_USER_ID" TEXT NOT NULL,
    "FROM_USER_ID" TEXT,
    "LAST_TEXT" TEXT NOT NULL,
    "SENT_TIMEST" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "TAPRI_CHAT_DETAILS_pkey" PRIMARY KEY ("ID")
);
